# Generated by Django 2.2 on 2021-03-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='Skills',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='resume',
            name='hobbies',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='references',
            field=models.TextField(default='', max_length=200),
        ),
    ]
