# Generated by Django 2.2 on 2021-03-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20210321_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='banner',
            field=models.ImageField(default='', upload_to='static/images/'),
        ),
    ]
