# Generated by Django 2.2 on 2021-03-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_resume_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='banner',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
